config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show", as: "home"

  resources :polls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :poll
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/polls_controller.rb
require "json"
require "http"

class PollsController < ApplicationController
    helper VotesHelper
    def index
        @polls = Poll.all
    end
    def show
        @poll = Poll.find(params[:id])
        @user = User.find(@poll.user_id)
        @poll.options = @poll.options.split(",").map do |option|
            addr = option.split(":^:")[1]
            option += ":^:" + JSON.parse(HTTP.get("https://api.zcha.in/v2/mainnet/accounts/#{addr}"))["balance"].to_s
        end.join(",")
    end

    def new
        @poll = Poll.new
    end

    def create
        @poll = Poll.new(poll_params)
        @poll.user_id = current_user.id
        @poll.options = @poll.options.split(",").map do |option|
            option = option.strip
            # Option.create(text: option, poll_id: @poll.id, taddr: random_burner_taddr())
            option += ":^:" + random_burner_taddr()
        end.join(",")
        if(@poll.save)
            redirect_to @poll
        else
            render "new"
        end
    end

    def destroy
        @poll = Poll.find(params[:id])
        @poll.destroy

        redirect_to polls_path
    end

    private def poll_params
        params.require(:poll).permit(:question, :options, :taddr)
    end

    private def update_votes()
        #Get each address total and update amounts
    end

    private def random_burner_taddr()
        head = "t1"
        middle = "burnvotertaddrxdlmaoepic"
        tail = [*("A"),*('C'..'H'),*("J".."N"),*("P".."Z"), *("a"),*('c'..'h'),*("j".."n"),*("p".."z"),*('0'),*("2".."9")].shuffle[0,9].join
        
        taddr = (head + middle + tail)
        return taddr if taddr.length == 35
        "Invalid taddr generated"
    end

end

app/controllers/votes_controller.rb
require "json"

# Valid burner addy - t1zcashburnerpollingaddressecksdeexd
# https://api.zcha.in/v2/mainnet/accounts/t1WLeAK9npDSRg7SAM5DMJSeYk45aCvpcdy
class VotesController < ApplicationController

    #These votes will be created by deposits to any taddr associated with a poll.
    # As soon as  a new transaction comes in, it should be burned.
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def show
       
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/votes_helper.rb
module VotesHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Burnvote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <header>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
  </header>
  <nav class="navbar navbar-expand-md navbar-light bg-dark">
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "View Polls", polls_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Create Poll", new_poll_path %></li>
        <% end %>
      </ul>
      </ul>
    </div>
  </nav>
    <section>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      <%= yield %>
    </section>
  </div>
  </body>
</html>

app/views/polls/index.html.erb
<h1>Polls</h1>
<% @polls.each do |poll| %>
    <div class="well">
        <h3><%= poll.question %></h3>
        <ul>
        <% poll.options.split(",").each do |option| %>
            <li><strong><%= option.split(":^:")[0] %></strong> : Vote to: <%= option.split(":^:")[1] %> </li>
        <% end %>
        </ul>
        <%= link_to "Details", poll_path(poll), :class => "btn btn-primary" %>
    </div>
<% end %> 

app/views/polls/new.html.erb
<h1>Add Poll</h1>
<%= form_for :poll, url: polls_path do |f| %>
    <%if @poll.errors.any? %>
        <% @poll.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :question %><br>
        <%=f.text_field(:question, {:class => "form-control"}) %>
    </p>

    <p>
        <%= f.label :options %><br>
        <%=f.text_area(:options, {:class => "form-control"}) %>
    </p>

    <p>
        <%= f.submit({:class => "btn btn-primary"}) %>
    </p>
<% end %>

app/views/polls/show.html.erb
<h2><%= @poll.question %></h2>
<h5>Posted by <%= @user.email %></h5>
<ul>
    <% @poll.options.split(",").each do |option| %>
        <li><strong><%= option.split(":^:")[0] %></strong> : Vote to: <%= option.split(":^:")[1] %> Balance: <%= option.split(":^:")[2] %> </li>
    <% end %>
    </ul>
<hr>
<% if current_user.id == @poll.user_id %>
    <%= link_to "Delete", poll_path(@poll), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger" %>
<% end %>
<hr>

app/views/welcome/show.html.erb
<h1>Welcome</h1>